/*
 * thermistor — 10K NTC (HVAC Type 2 / Type 3) temperature sensing for ESP32.
 *
 * Split into:
 *   - PURE conversion helpers (no ESP dependency) — unit-testable on a host:
 *       ntc_resistance_from_mv(), ntc_temp_c_from_resistance(), ntc_temp_c_from_mv()
 *   - a small ADC-backed driver (ESP-IDF) that samples, converts, filters and
 *     applies a user calibration offset: thermistor_init()/thermistor_read().
 *
 * Curve data lives in ntc_type2_lut.inc / ntc_type3_lut.inc (generated by
 * tools/gen_ntc_lut.py). Replace those with datasheet tables for field accuracy.
 */
#ifndef THERMISTOR_H
#define THERMISTOR_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    NTC_TYPE_2 = 0,   /* 10K "Type 2" / 10K-2 */
    NTC_TYPE_3,       /* 10K "Type 3" / 10K-3 */
} ntc_type_t;

/* One (temperature, resistance) point. temp in 0.01 C, resistance in ohms. */
typedef struct {
    int32_t temp_c100;
    int32_t r_ohm;
} ntc_lut_point_t;

/* ---- PURE conversion (no hardware) ---------------------------------------- */

/*
 * Node voltage (mV, NTC on the bottom leg of the divider) -> NTC resistance.
 *   R_ntc = R_fix * V / (Vref - V)
 * Returns a very large value as V -> Vref (open sensor) and ~0 as V -> 0.
 */
float ntc_resistance_from_mv(float v_mv, float vref_mv, float r_fix_ohm);

/*
 * NTC resistance (ohms) -> temperature (C), using the per-type LUT with linear
 * interpolation. Beyond the table ends it extrapolates from the end segment.
 */
float ntc_temp_c_from_resistance(ntc_type_t type, float r_ohm);

/* Convenience: node voltage -> temperature. */
float ntc_temp_c_from_mv(ntc_type_t type, float v_mv, float vref_mv, float r_fix_ohm);

/* ---- ADC-backed driver (ESP-IDF) ------------------------------------------ */

typedef struct {
    int        adc_gpio;       /* ADC1-capable GPIO (0..6 on ESP32-C6)         */
    int        r_fix_ohm;      /* divider reference resistor                   */
    int        vref_mv;        /* divider top-rail voltage (mV)                */
    ntc_type_t type;           /* NTC_TYPE_2 or NTC_TYPE_3                      */
    int        median_n;       /* raw samples per read (odd; 1..15)            */
    int        ema_alpha_pct;  /* output smoothing 1..100 (100 = no smoothing) */
    int        offset_c100;    /* user calibration offset in 0.01 C            */
} thermistor_config_t;

/* Initialize the ADC (oneshot + calibration). Returns ESP_OK on success. */
int thermistor_init(const thermistor_config_t *cfg);

/*
 * Read the filtered room temperature.
 *   *temp_c  <- current temperature in C (valid unless *fault)
 *   *fault   <- true if the sensor looks open/shorted (rail-pinned reading)
 * Returns ESP_OK on a completed measurement.
 */
int thermistor_read(float *temp_c, bool *fault);

/* Update the calibration offset at runtime (0.01 C units). */
void thermistor_set_offset_c100(int offset_c100);

/* Switch the active NTC curve at runtime. */
void thermistor_set_type(ntc_type_t type);

#ifdef __cplusplus
}
#endif

#endif /* THERMISTOR_H */
