#!/usr/bin/env python3
"""
gen_ntc_lut.py — generate a resistance/temperature lookup table for a 10K NTC
thermistor (HVAC Type 2 or Type 3) as a C initializer for the `thermistor`
component.

Two data sources are supported:

  1. --beta / --type   Compute R(T) from the beta model:
                          R(T) = R0 * exp( beta * (1/T - 1/T0) )
                        with R0 = 10k at T0 = 25 C. Quick, approximate.

  2. --csv FILE        Use the MANUFACTURER R-T table (recommended for accuracy).
                        CSV columns: temperature_C,resistance_ohm

The emitted table is temperature-ascending (resistance-descending), suitable for
the interpolation routine in thermistor.c.

Examples
--------
  # From nominal beta for a Type 3 curve, -20..60 C in 5 C steps:
  python3 tools/gen_ntc_lut.py --type 3 --tmin -20 --tmax 60 --step 5 \
      > firmware/components/thermistor/ntc_type3_lut.inc

  # From a datasheet R-T table (authoritative):
  python3 tools/gen_ntc_lut.py --csv type2_datasheet.csv --name ntc_type2_lut \
      > firmware/components/thermistor/ntc_type2_lut.inc

NOTE: The beta values below are NOMINAL. HVAC "Type 2" and "Type 3" are defined by
their manufacturer R-T tables; prefer --csv from the datasheet for field accuracy.
"""
import argparse
import math
import sys

R0 = 10000.0          # ohms at T0
T0 = 25.0 + 273.15    # Kelvin

# Nominal beta (25/85) values. VALIDATE against your sensor datasheet.
NOMINAL_BETA = {
    2: 3891.0,   # 10K "Type 2" / 10K-2 (nominal)
    3: 3976.0,   # 10K "Type 3" / 10K-3 (nominal)
}


def r_from_beta(temp_c: float, beta: float) -> float:
    """Resistance (ohms) at temp_c using the beta model."""
    t = temp_c + 273.15
    return R0 * math.exp(beta * (1.0 / t - 1.0 / T0))


def build_from_beta(beta, tmin, tmax, step):
    rows = []
    t = tmin
    while t <= tmax + 1e-9:
        rows.append((round(t, 2), r_from_beta(t, beta)))
        t += step
    return rows


def build_from_csv(path):
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.lower().startswith("temp") or line.startswith("#"):
                continue
            parts = line.replace(",", " ").split()
            if len(parts) < 2:
                continue
            rows.append((float(parts[0]), float(parts[1])))
    rows.sort(key=lambda r: r[0])  # ascending temperature
    return rows


def emit_c(rows, name):
    print(f"/* Auto-generated by tools/gen_ntc_lut.py — do not edit by hand. */")
    print(f"/* Table is temperature-ascending; resistance in ohms. */")
    print(f"static const ntc_lut_point_t {name}[] = {{")
    for t_c, r_ohm in rows:
        # temp stored in 0.01 C; resistance rounded to whole ohms
        print(f"    {{ {int(round(t_c * 100)):>7d}, {int(round(r_ohm)):>7d} }},"
              f"  /* {t_c:6.2f} C */")
    print("};")
    print(f"static const int {name}_len = "
          f"(int)(sizeof({name}) / sizeof({name}[0]));")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--type", type=int, choices=(2, 3),
                     help="use nominal beta for HVAC 10K Type 2 or Type 3")
    src.add_argument("--beta", type=float, help="explicit beta (25/85) value")
    src.add_argument("--csv", help="manufacturer R-T CSV: temperature_C,resistance_ohm")
    ap.add_argument("--tmin", type=float, default=-20.0)
    ap.add_argument("--tmax", type=float, default=60.0)
    ap.add_argument("--step", type=float, default=5.0)
    ap.add_argument("--name", default=None, help="C array name")
    args = ap.parse_args()

    if args.csv:
        rows = build_from_csv(args.csv)
        name = args.name or "ntc_custom_lut"
    else:
        beta = args.beta if args.beta else NOMINAL_BETA[args.type]
        rows = build_from_beta(beta, args.tmin, args.tmax, args.step)
        default_name = f"ntc_type{args.type}_lut" if args.type else "ntc_beta_lut"
        name = args.name or default_name
        print(f"/* beta model: R0=10k @25C, beta={beta} K */", file=sys.stderr)

    if len(rows) < 2:
        sys.exit("error: need at least 2 points")
    emit_c(rows, name)


if __name__ == "__main__":
    main()
